### ISSUE TITLE
devops - 數據監控

### ISSUE THREAD

**Issue by yudady01** [yudady/yudady.github.io#2]
- [ ] Prometheus
  - [ ] #3
  - [x] #5
  - [x] #6
  - [ ] kubernetes微服务实践 [spring2go/k8s-msa-in-action-ppt: 课程《kubernetes微服务实践》的ppt](https://github.com/spring2go/k8s-msa-in-action-ppt)
    - [ ] 3. [如何安装Docker Desktop for Mac_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV16E411u75h/?vd_source=6bd04a20c72eb5cca642210346af7081)
    - [ ] 4. [SpringCloud微服务应用_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1o5411x7ML/?vd_source=6bd04a20c72eb5cca642210346af7081)
    - [ ] 5. [Kubernetes基本概念和应用_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1Ja4y1x748/?vd_source=6bd04a20c72eb5cca642210346af7081)
    - [ ] 6. [阿里云Kuberneters微服务部署案例_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1UA41187Du/?vd_source=6bd04a20c72eb5cca642210346af7081)
    - [ ] 7. [Kubernetes和微服务监控体系_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1Qi4y1b79r/?vd_source=6bd04a20c72eb5cca642210346af7081)
    - [ ] 8. #7 
    - [ ] 9 [Kubernetes和微服务CI/CD_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1ut4y1U7Tz/?vd_source=6bd04a20c72eb5cca642210346af7081)
    - [ ] 10. [深入理解Kubernetes网络_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1Ft4y117Ch/?vd_source=6bd04a20c72eb5cca642210346af7081)

---

# action in k8s

- [ ] kube-prometheus-stack
  - [ ] [kube-prometheus-stack 12.8.0 · worawutchan/prometheus-worawutchan](https://artifacthub.io/packages/helm/prometheus-worawutchan/kube-prometheus-stack)
  - [ ] [Prometheus Monitoring - Steps to monitor third-party apps using Prometheus Exporter | Part 2 - YouTube](https://www.youtube.com/watch?v=mLPg49b33sA&list=PL9N-xQIOqcpHnLysc8cwP4Mk9dG0l64qq&index=2&t=417s)

[Gather Metrics with Spring Boot using Prometheus & Grafana | VMware Tanzu Developer Center](https://tanzu.vmware.com/developer/guides/spring-prometheus/)

**kind: ServiceMonitor**
    **release: prometheus**

```yml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-prometheus-demo-service-monitor
spec:
  selector:
    matchLabels:
      app: spring-prometheus-demo
  endpoints:
  - port: http-traffic
    path: "/actuator/prometheus"
```

---
